"""Add missing updated_at column to co_targets

Revision ID: 9b8013b0ad0a
Revises: 001
Create Date: 2025-09-13 14:37:13.160206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8013b0ad0a'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists before adding
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('assessment_weights')]
    if 'updated_at' not in columns:
        op.add_column('assessment_weights', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('assessment_weights', 'weight_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    # Check if indexes already exist before creating
    indexes = [idx['name'] for idx in inspector.get_indexes('assessment_weights')]
    if 'ix_assessment_weights_id' not in indexes:
        op.create_index(op.f('ix_assessment_weights_id'), 'assessment_weights', ['id'], unique=False)
    
    attainment_audit_indexes = [idx['name'] for idx in inspector.get_indexes('attainment_audit')]
    if 'ix_attainment_audit_id' not in attainment_audit_indexes:
        op.create_index(op.f('ix_attainment_audit_id'), 'attainment_audit', ['id'], unique=False)
    
    co_definitions_indexes = [idx['name'] for idx in inspector.get_indexes('co_definitions')]
    if 'ix_co_definitions_id' not in co_definitions_indexes:
        op.create_index(op.f('ix_co_definitions_id'), 'co_definitions', ['id'], unique=False)
    # Check if co_po_matrix updated_at column exists
    co_po_matrix_columns = [col['name'] for col in inspector.get_columns('co_po_matrix')]
    if 'updated_at' not in co_po_matrix_columns:
        op.add_column('co_po_matrix', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # co_po_matrix uses co_code and po_code (strings), not co_id and po_id (integers)
    # Skip column alterations for non-existent columns
    co_po_matrix_indexes = [idx['name'] for idx in inspector.get_indexes('co_po_matrix')]
    if 'ix_co_po_matrix_id' not in co_po_matrix_indexes:
        op.create_index(op.f('ix_co_po_matrix_id'), 'co_po_matrix', ['id'], unique=False)
    # Check if co_targets updated_at column exists
    co_targets_columns = [col['name'] for col in inspector.get_columns('co_targets')]
    if 'updated_at' not in co_targets_columns:
        op.add_column('co_targets', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # co_targets uses co_code (string), not co_id (integer)
    # Skip column alteration for non-existent column
    op.alter_column('co_targets', 'target_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('co_targets', 'l1_threshold',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('co_targets', 'l2_threshold',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('co_targets', 'l3_threshold',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    # Check if index already exists before creating
    co_targets_indexes = [idx['name'] for idx in inspector.get_indexes('co_targets')]
    if 'ix_co_targets_id' not in co_targets_indexes:
        op.create_index(op.f('ix_co_targets_id'), 'co_targets', ['id'], unique=False)
    op.alter_column('indirect_attainment', 'value_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    # Check if index already exists before creating
    indirect_attainment_indexes = [idx['name'] for idx in inspector.get_indexes('indirect_attainment')]
    if 'ix_indirect_attainment_id' not in indirect_attainment_indexes:
        op.create_index(op.f('ix_indirect_attainment_id'), 'indirect_attainment', ['id'], unique=False)
    # Check if index already exists before creating
    po_definitions_indexes = [idx['name'] for idx in inspector.get_indexes('po_definitions')]
    if 'ix_po_definitions_id' not in po_definitions_indexes:
        op.create_index(op.f('ix_po_definitions_id'), 'po_definitions', ['id'], unique=False)
    # question_co_weights uses co_code (string), not co_id (integer)
    # Skip column alteration for non-existent column
    op.alter_column('question_co_weights', 'weight_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    # Check if index already exists before creating
    question_co_weights_indexes = [idx['name'] for idx in inspector.get_indexes('question_co_weights')]
    if 'ix_question_co_weights_id' not in question_co_weights_indexes:
        op.create_index(op.f('ix_question_co_weights_id'), 'question_co_weights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_co_weights_id'), table_name='question_co_weights')
    op.alter_column('question_co_weights', 'weight_pct',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('question_co_weights', 'co_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_po_definitions_id'), table_name='po_definitions')
    op.drop_index(op.f('ix_indirect_attainment_id'), table_name='indirect_attainment')
    op.alter_column('indirect_attainment', 'value_pct',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_co_targets_id'), table_name='co_targets')
    op.alter_column('co_targets', 'l3_threshold',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('co_targets', 'l2_threshold',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('co_targets', 'l1_threshold',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('co_targets', 'target_pct',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('co_targets', 'co_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('co_targets', 'updated_at')
    op.drop_index(op.f('ix_co_po_matrix_id'), table_name='co_po_matrix')
    op.alter_column('co_po_matrix', 'po_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('co_po_matrix', 'co_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('co_po_matrix', 'updated_at')
    op.drop_index(op.f('ix_co_definitions_id'), table_name='co_definitions')
    op.drop_index(op.f('ix_attainment_audit_id'), table_name='attainment_audit')
    op.drop_index(op.f('ix_assessment_weights_id'), table_name='assessment_weights')
    op.alter_column('assessment_weights', 'weight_pct',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.drop_column('assessment_weights', 'updated_at')
    # ### end Alembic commands ###